### ISSUE TITLE
The collision detection isn't reliable

### ISSUE THREAD

**Issue by CiurkitboyN** [SneezingCactus/gmmaker#6]
Often the collision system doesn't work and it doesn't detect it or it only runs the code for one person rather than both

**Comment by SneezingCactus** [comment]
It's been a year and a half since this issue, so I'll just state the following: I won't fix any bugs where the physics engine is the one at fault and not GMMaker itself. Then again, this issue is 1.5 years old, so there's a chance that this was actually a GMMaker issue, and thus it might have been resolved by now. If the issue persists and you can prove that GMMaker is at fault, feel free to reopen this issue.
